=== dydko1/Scraper-6-Minute-English/BBCScraper/WebContent/myfile.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT BBC-6-minute-english (EpisodeId)+>
<!ATTLIST BBC-6-minute-english
  xmlns CDATA #FIXED ''>

<!ELEMENT EpisodeId (Title,Keynote,Episode,LessonUrl,ImgUrl,Mp3Url,
                     PdfUrl,Ts)>
<!ATTLIST EpisodeId
  xmlns CDATA #FIXED ''
  id CDATA #REQUIRED>

<!ELEMENT Title (#PCDATA)>
<!ATTLIST Title
  xmlns CDATA #FIXED ''>

<!ELEMENT Keynote (#PCDATA)>
<!ATTLIST Keynote
  xmlns CDATA #FIXED ''>

<!ELEMENT Episode (#PCDATA)>
<!ATTLIST Episode
  xmlns CDATA #FIXED ''>

<!ELEMENT LessonUrl (#PCDATA)>
<!ATTLIST LessonUrl
  xmlns CDATA #FIXED ''>

<!ELEMENT ImgUrl (#PCDATA)>
<!ATTLIST ImgUrl
  xmlns CDATA #FIXED ''>

<!ELEMENT Mp3Url (#PCDATA)>
<!ATTLIST Mp3Url
  xmlns CDATA #FIXED ''>

<!ELEMENT PdfUrl (#PCDATA)>
<!ATTLIST PdfUrl
  xmlns CDATA #FIXED ''>

<!ELEMENT Ts (#PCDATA)>
<!ATTLIST Ts
  xmlns CDATA #FIXED ''>

=== dydko1/Scraper-6-Minute-English/BBCScraper/WebContent/myfile.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE BBC-6-minute-english PUBLIC "BBC SYSTEM" "myfile.dtd">
<BBC-6-minute-english>
<EpisodeId id="254">
<Title>Coffee cups: Do you use your own?</Title>
<Keynote>Does recycling coffee cups make a difference?</Keynote>
<Episode>Episode 190801 / 01 Aug 2019</Episode>
<LessonUrl>http://www.bbc.co.uk/learningenglish/english/features/6-minute-english/ep-190801</LessonUrl>
<ImgUrl>http://ichef.bbci.co.uk/images/ic/976xn/p07bssk1.jpg</ImgUrl>
<Mp3Url>http://downloads.bbc.co.uk/learningenglish/features/6min/190801_6min_english_coffee_cups_download.mp3</Mp3Url>
<PdfUrl>http://downloads.bbc.co.uk/learningenglish/features/6min/190801_6min_english_coffee_cups.pdf</PdfUrl>
</EpisodeId>
<EpisodeId id="253">
<Title>Are you at risk from online fraud?</Title>
<Keynote>Falling for fraud</Keynote>
<Episode>Episode 190725 / 25 Jul 2019</Episode>
<LessonUrl>http://www.bbc.co.uk/learningenglish/english/features/6-minute-english/ep-190725</LessonUrl>
<ImgUrl>http://ichef.bbci.co.uk/images/ic/624xn/p07gly9f.jpg</ImgUrl>
<Mp3Url>http://downloads.bbc.co.uk/learningenglish/features/6min/190725_6_minute_english_fraud_download.mp3</Mp3Url>
<PdfUrl>http://downloads.bbc.co.uk/learningenglish/features/6min/190725_6_minute_english_fraud.pdf</PdfUrl>
</EpisodeId>
<EpisodeId id="252">
<Title>Is shame always bad?</Title>
<Keynote>Why is 'shame' the emotion of now?</Keynote>
<Episode>Episode 190718 / 18 Jul 2019</Episode>
<LessonUrl>http://www.bbc.co.uk/learningenglish/english/features/6-minute-english/ep-190718</LessonUrl>
<ImgUrl>http://ichef.bbci.co.uk/images/ic/624xn/p07g8th0.jpg</ImgUrl>
<Mp3Url>http://downloads.bbc.co.uk/learningenglish/features/6min/190718_6min_english_shame_download.mp3</Mp3Url>
<PdfUrl>http://downloads.bbc.co.uk/learningenglish/features/6min/190718_6min_english_shame.pdf</PdfUrl>
</EpisodeId>
<EpisodeId id="251">
<Title>Do you care if you're poor when you're old?</Title>
<Keynote>Are you planning for a comfortable retirement?</Keynote>
<Episode>Episode 190711 / 11 Jul 2019</Episode>
<LessonUrl>http://www.bbc.co.uk/learningenglish/english/features/6-minute-english/ep-190711</LessonUrl>
<ImgUrl>http://ichef.bbci.co.uk/images/ic/624xn/p07d0gh5.jpg</ImgUrl>
<Mp3Url>http://downloads.bbc.co.uk/learningenglish/features/6min/190711_6min_english_money_and_lifestyle_download.mp3</Mp3Url>
<PdfUrl>http://downloads.bbc.co.uk/learningenglish/features/6min/190711_6min_english_money_and_lifestyle.pdf</PdfUrl>
</EpisodeId>
<EpisodeId id="250">
<Title>Womenâ€™s football</Title>
<Keynote>FIFA Women's World Cup 2019</Keynote>
<Episode>Episode 190704 / 04 Jul 2019</Episode>
<LessonUrl>http://www.bbc.co.uk/learningenglish/english/features/6-minute-english/ep-190704</LessonUrl>
<ImgUrl>http://ichef.bbci.co.uk/images/ic/624xn/p07fpg5b.jpg</ImgUrl>
<Mp3Url>http://downloads.bbc.co.uk/learningenglish/features/6min/190704_6_minute_english_womens_football_download.mp3</Mp3Url>
<PdfUrl>http://downloads.bbc.co.uk/learningenglish/features/6min/190704_6_minute_english_womans_football.pdf</PdfUrl>
</EpisodeId>
<EpisodeId id="248">
<Title>The business of eSports</Title>
<Keynote>Game on for eSports!</Keynote>
<Episode>Episode 190627 / 27 Jun 2019</Episode>
<LessonUrl>http://www.bbc.co.uk/learningenglish/english/features/6-minute-english/ep-190627</LessonUrl>
<ImgUrl>http://ichef.bbci.co.uk/images/ic/624xn/p07f6j63.jpg</ImgUrl>
<Mp3Url>http://downloads.bbc.co.uk/learningenglish/features/6min/190627_6_minute_english_esports_download.mp3</Mp3Url>
<PdfUrl>http://downloads.bbc.co.uk/learningenglish/features/6min/190627_6min_english_esports.pdf</PdfUrl>
</EpisodeId>
<EpisodeId id="247">
<Title>Can death metal bring you joy?</Title>
<Keynote>Does fast, loud, aggressive, guitar-based music inspire violence or happiness?</Keynote>
<Episode>Episode 190620 / 20 Jun 2019</Episode>
<LessonUrl>http://www.bbc.co.uk/learningenglish/english/features/6-minute-english/ep-190620</LessonUrl>
<ImgUrl>http://ichef.bbci.co.uk/images/ic/624xn/p07b0dd0.jpg</ImgUrl>
<Mp3Url>http://downloads.bbc.co.uk/learningenglish/features/6min/190620_6min_english_death_metal_download.mp3</Mp3Url>
<PdfUrl>http://downloads.bbc.co.uk/learningenglish/features/6min/190620_6min_english_death_metal.pdf</PdfUrl>
</EpisodeId>
<EpisodeId id="246">
<Title>Is talking on the phone embarrassing?</Title>
<Keynote>Is talking on the telephone embarrassing?</Keynote>
<Episode>Episode 190613 / 13 Jun 2019</Episode>
<LessonUrl>http://www.bbc.co.uk/learningenglish/english/features/6-minute-english/ep-190613</LessonUrl>
<ImgUrl>http://ichef.bbci.co.uk/images/ic/624xn/p07cjxgn.jpg</ImgUrl>
<Mp3Url>http://downloads.bbc.co.uk/learningenglish/features/6min/le_190613_6min_phone_embarrassing_download.mp3</Mp3Url>
<PdfUrl>http://downloads.bbc.co.uk/learningenglish/features/6min/190613_6min_phone_embarrassing.pdf</PdfUrl>
</EpisodeId>
<EpisodeId id="245">
<Title>Women and motorbikes</Title>
<Keynote>Why do we associate motorcycles with men?</Keynote>
<Episode>Episode 190606 / 06 Jun 2019</Episode>
<LessonUrl>http://www.bbc.co.uk/learningenglish/english/features/6-minute-english/ep-190606</LessonUrl>
<ImgUrl>http://ichef.bbci.co.uk/images/ic/624xn/p0765tt1.jpg</ImgUrl>
<Mp3Url>http://downloads.bbc.co.uk/learningenglish/features/6min/190606_6min_english_motorcycles_download.mp3</Mp3Url>
<PdfUrl>http://downloads.bbc.co.uk/learningenglish/features/6min/190606_6min_english_motorcycles.pdf</PdfUrl>
</EpisodeId>
<EpisodeId id="244">
<Title>Vampire shoppers</Title>
<Keynote>Shopping online in the middle of the night is becoming popular but, is it always a good idea?</Keynote>
<Episode>Episode 190530 / 30 May 2019</Episode>
<LessonUrl>http://www.bbc.co.uk/learningenglish/english/features/6-minute-english/ep-190530</LessonUrl>
<ImgUrl>http://ichef.bbci.co.uk/images/ic/624xn/p075nd2j.jpg</ImgUrl>
<Mp3Url>http://downloads.bbc.co.uk/learningenglish/features/6min/190530_6min_english_vampire_shoppers_download.mp3</Mp3Url>
<PdfUrl>http://downloads.bbc.co.uk/learningenglish/features/6min/190530_6min_english_vampire_shoppers.pdf</PdfUrl>
</EpisodeId>
<EpisodeId id="243">
<Title>What to do when you can't sleep</Title>
<Keynote>Is there anything more frustrating?</Keynote>
<Episode>Episode 190523 / 23 May 2019</Episode>
<LessonUrl>http://www.bbc.co.uk/learningenglish/english/features/6-minute-english/ep-190523</LessonUrl>
<ImgUrl>http://ichef.bbci.co.uk/images/ic/624xn/p07b2zrn.jpg</ImgUrl>
<Mp3Url>http://downloads.bbc.co.uk/learningenglish/features/6min/190523_6min_when_you_cant_sleep_download.mp3</Mp3Url>
<PdfUrl>http://downloads.bbc.co.uk/learningenglish/features/6min/190523_6min_when_you_cant_sleep.pdf</PdfUrl>
</EpisodeId>
<EpisodeId id="242">
<Title>Being slim: Is it in our genes?</Title>
<Keynote>Studies have shown that about 40% of the variation in a person's weight is influenced by genes.</Keynote>
<Episode>Episode 190516 / 16 May 2019</Episode>
<LessonUrl>http://www.bbc.co.uk/learningenglish/english/features/6-minute-english/ep-190516</LessonUrl>
<ImgUrl>http://ichef.bbci.co.uk/images/ic/624xn/p0759jv6.jpg</ImgUrl>
<Mp3Url>http://downloads.bbc.co.uk/learningenglish/features/6min/190516_6min_english_slimness_download.mp3</Mp3Url>
<PdfUrl>http://downloads.bbc.co.uk/learningenglish/features/6min/190516_6min_english_slimness.pdf</PdfUrl>
</EpisodeId>
<EpisodeId id="241">
<Title>Can we trust a smart speaker?</Title>
<Keynote>Do smart speakers make life easier or spy on you?</Keynote>
<Episode>Episode 190509 / 09 May 2019</Episode>
<LessonUrl>http://www.bbc.co.uk/learningenglish/english/features/6-minute-english/ep-190509</LessonUrl>
<ImgUrl>http://ichef.bbci.co.uk/images/ic/624xn/p072zj58.jpg</ImgUrl>
<Mp3Url>http://downloads.bbc.co.uk/learningenglish/features/6min/190509_6min_english_smart_speakers_download.mp3</Mp3Url>
<PdfUrl>http://downloads.bbc.co.uk/learningenglish/features/6min/190509_6min_english_smart_speakers.pdf</PdfUrl>
</EpisodeId>
<EpisodeId id="240">
<Title>Evolution and anxiety</Title>
<Keynote>Has anxiety been good for humans?</Keynote>
<Episode>Episode 190502 / 02 May 2019</Episode>
<LessonUrl>http://www.bbc.co.uk/learningenglish/english/features/6-minute-english/ep-190502</LessonUrl>
<ImgUrl>http://ichef.bbci.co.uk/images/ic/624xn/p074gzql.jpg</ImgUrl>
<Mp3Url>http://downloads.bbc.co.uk/learningenglish/features/6min/190502_6min_english_evolution_and_mental_health_download.mp3</Mp3Url>
<PdfUrl>http://downloads.bbc.co.uk/learningenglish/features/6min/190502_6min_english_evolution_and_mental_health.pdf</PdfUrl>
</EpisodeId>
<EpisodeId id="239">
<Title>The rise in popularity of the comfy shoe</Title>
<Keynote>Everyone's wearing them!</Keynote>
<Episode>Episode 190425 / 25 Apr 2019</Episode>
<LessonUrl>http://www.bbc.co.uk/learningenglish/english/features/6-minute-english/ep-190425</LessonUrl>
<ImgUrl>http://ichef.bbci.co.uk/images/ic/624xn/p071lclk.jpg</ImgUrl>
<Mp3Url>http://downloads.bbc.co.uk/learningenglish/features/6min/190425_6min_comfy_footwear_download.mp3</Mp3Url>
<PdfUrl>http://downloads.bbc.co.uk/learningenglish/features/6min/190425_6min_comfy_footwear.pdf</PdfUrl>
</EpisodeId>
<EpisodeId id="238">
<Title>Rabbits: cuddly friends or cunning tricksters?</Title>
<Keynote>Neil and Rob talk about the animal symbol of Easter in literature and in the real world.</Keynote>
<Episode>Episode 190418 / 18 Apr 2019</Episode>
<LessonUrl>http://www.bbc.co.uk/learningenglish/english/features/6-minute-english/ep-190418</LessonUrl>
<ImgUrl>http://ichef.bbci.co.uk/images/ic/624xn/p071yyhn.jpg</ImgUrl>
<Mp3Url>http://downloads.bbc.co.uk/learningenglish/features/6min/190418_6min_english_rabbits_download.mp3</Mp3Url>
<PdfUrl>http://downloads.bbc.co.uk/learningenglish/features/6min/190418_6min_english_rabbit.pdf</PdfUrl>
</EpisodeId>
<EpisodeId id="237">
<Title>The decluttering trend</Title>
<Keynote>Is it time you decluttered?</Keynote>
<Episode>Episode 190411 / 11 Apr 2019</Episode>
